version = 1

test_patterns = [
  "**/test/**",
  "**/*.test.*"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true